name: build

on:
  push:
    paths: [ 'src/**', '.github/workflows/build.yml' ]
  pull_request:
    paths: [ 'src/**', '.github/workflows/build.yml' ]

# env:
#   Configuration type to build.
#   You can convert this to a build matrix if you need coverage of multiple configuration types.
#   https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
#   BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Load Conan cache
      uses: actions/cache@v3
      with:
        path: ./.conan/data
        key: ${{ runner.os }}-conan-${{ hashFiles('src/conanfile.txt') }}
    
    - name: Restore NuGet packages
      run: nuget restore
    
    - name: Setup Conan
      run: pip install conan

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Build
      run: msbuild /p:Configuration=Release /p:Platform=x64 src/DEPLOY

    - name: Save hash
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Store build
      uses: actions/upload-artifact@v3
      with: 
          name: Magpie_dev_${{ steps.vars.outputs.sha_short }}
          path: ./publish
